import type { Metadata } from "next";
import { JetBrains_Mono, Figtree, Roboto_Slab } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { ImpersonationIndicator } from "@/components/auth/impersonation-indicator";

const fontSans = Figtree({
	subsets: ["latin"],
	variable: "--font-sans",
});

const fontSerif = Roboto_Slab({
	subsets: ["latin"],
	variable: "--font-serif",
});

const fontMono = JetBrains_Mono({
	subsets: ["latin"],
	variable: "--font-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			className={cn(
				`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} h-full antialiased`,
			)}
		>
			<body className='min-h-full flex flex-col'>
				{children}
				<Toaster position='top-left' />
				<ImpersonationIndicator />
			</body>
		</html>
	);
}
